### ISSUE TITLE
App fails to build after adding this plugin

### ISSUE THREAD

**Issue by vorlovsky** [leanflutter/screen_retriever#18]
Windows app fails fo build and run right after adding this plugin as a dependency (on its own or with another plugin, e.g. windows_manager).

Steps:
1. Create a new Flutter application project
2. Run `flutter pub add screen_retriever`
3. See the debug console in VS Code
4 (optional). Try to run the app in debug mode

The error immediately appearing in the console is:

> Creating symlink from source to dest failed with ERROR_INVALID_FUNCTION. Try moving your Flutter project to the same drive as your Flutter SDK.

For me, the project and Flutter SDK are in the same parent folder. Most likely reason is that all this files are stored on exFAT volume.

FYI:
Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    • Flutter version 3.16.2
    • Framework revision 9e1c857886 (5 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

**Comment by lijy91** [comment]
It doesn't look like it's caused by a plugin.

https://stackoverflow.com/questions/77753875/flutter-windows-build-error-creating-symlink-from-source-to-dest-failed-with-e
https://www.reddit.com/r/flutterhelp/comments/18egm5b/symlink_error_after_moving_to_new_external_drive/
