### ISSUE TITLE
Question - Does screen_retriever provide keyboard cursor position on Linux?

### ISSUE THREAD

**Issue by dinbtechit** [leanflutter/screen_retriever#2]
Does screen_retriever provide keyboard cursor position on Linux?

I am working on a floating emoji keyword in flutter. I would like to show the emoji keyboard when the user presses `win` + `.`. I was wondering if I can use screen_retriever to get the (x, y) coordinates of the keyboard cursor on the screen.

**Comment by lijy91** [comment]
I don't think this should be provided by screen_retriever

**Comment by dinbtechit** [comment]
Interesting, it does provide the mouse cursor x, y position. Thought it would be helpful to have a keyboard cursor location as well. Thank you tho.
