### ISSUE TITLE
Windows compilation fails, type errors

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [leanflutter/screen_retriever#6]
The following code fails to compile for me:

```cpp
BOOL CALLBACK MonitorRepresentationEnumProc(HMONITOR monitor,
                                            HDC hdc,
                                            LPRECT clip,
                                            LPARAM list_ref) {
  flutter::EncodableValue* monitors =
      reinterpret_cast<flutter::EncodableValue*>(list_ref);
  flutter::EncodableMap display = MonitorToEncodableMap(monitor);
  std::get<flutter::EncodableList>(*monitors).push_back(display);
  return TRUE;
}
```

With the following error:

error: no matching member function for call to 'push_back'
  std::get<EncodableList>(*monitors).push_back(display);
third_party/lexan/libcxx/include/vector:586:62: note: candidate function not viable: no known conversion from 'EncodableMap' (aka 'map<EncodableValue, EncodableValue>') to 'const value_type' (aka 'const flutter::EncodableValue') for 1st argument
    _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(const_reference __x);

Similarly, the plugin return block for `GetAllDisplays`:

```cpp
void ScreenRetrieverPlugin::GetAllDisplays(
    const flutter::MethodCall<flutter::EncodableValue>& method_call,
    std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>> result) {
  flutter::EncodableValue displays(std::in_place_type<flutter::EncodableList>);

  ::EnumDisplayMonitors(nullptr, nullptr, MonitorRepresentationEnumProc,
                        reinterpret_cast<LPARAM>(&displays));

  flutter::EncodableMap result_data = flutter::EncodableMap();
  result_data[flutter::EncodableValue("displays")] = displays;

  result->Success(result_data);
}
```

Causes this compilation error:

error: no matching member function for call to 'Success'
  result->Success(result_data);
third_party/flutter_engine/shell/platform/common/client_wrapper/include/flutter/method_result.h:29:8: note: candidate function not viable: no known conversion from 'EncodableMap' (aka 'map<EncodableValue, EncodableValue>') to 'const flutter::EncodableValue' for 1st argument

Does the Windows package successfully compile for anyone else? I'm using the latest plugin version and the latest stable Flutter engine version.

**Comment by ChristianEdwardPadilla** [comment]
I think both the `display` and `result_data` need to be wrapped in `EncodableValue`. Doing that locally has fixed my compilation errors.

**Comment by lijy91** [comment]
Please update to 0.1.6
